### ISSUE TITLE
Academic Record Management Policy link does not have an actual link URL in the anchor tag.

### ISSUE THREAD

**Issue by CodeSchwert** [Developers-Institute-Internal/Student-Refunds-Withdrawals-Fee-Protection-Policy#2]
Line 80 - Anchor tag `href` has a placeholder link.

**Comment by ngariki** [comment]
@CodeSchwert I'd put it in there as a placeholder but I've deleted the tag for now until we go back into that doc together when you have time. Will leave this issue open until it's done.
