### ISSUE TITLE
Student Refunds, Withdrawals and Fee Protection Policy - Please rewrite in `Markdown`. There are broken elements, possibly due to formatting or nested HTML tags.

### ISSUE THREAD

**Issue by CodeSchwert** [Developers-Institute-Internal/Student-Refunds-Withdrawals-Fee-Protection-Policy#4]

**Comment by ngariki** [comment]
@CodeSchwert thanks for this - we continued as per how Steve had started but def feel like it was way more complicated than needed to be! Also githib pages is good approach I think. Found the guide... will do next one this way. And will use markdown.
